import "./globals.css";
import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import NavBar from "./NavBar";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import AuthProvider from "./auth/Provider";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

const dmSans = DM_Sans({subsets: ['latin']})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	openGraph: {
		title: '...',
		description: '...'
	}
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`flex min-h-screen bg-background transition-all duration-300 ease-in-out ${dmSans.className}`}
			>
				<AuthProvider>
					<NextSSRPlugin
						/**
						 * The `extractRouterConfig` will extract **only** the route configs
						 * from the router to prevent additional information from being
						 * leaked to the client. The data passed to the client is the same
						 * as if you were to fetch `/api/uploadthing` directly.
						 */
						routerConfig={extractRouterConfig(ourFileRouter)}
					/>
					<NavBar />
					<main className="w-full h-full p-4 transform transition-all duration-300 ease-in-out">
						<Providers>{children}</Providers>
					</main>
				</AuthProvider>
			</body>
		</html>
	);
}
